/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface Account {
  id: Generated<number>;
  password: string;
  username: string;
}

export interface Article {
  content_md: string;
  created_at: Generated<Date>;
  dec: Generated<number | null>;
  description: string;
  fov_height: Generated<number | null>;
  fov_rotation: Generated<number | null>;
  fov_width: Generated<number | null>;
  id: Generated<string>;
  object_id: Generated<unknown | null>;
  ra: Generated<number | null>;
  title: string;
  updated_at: Generated<Date>;
}

export interface ArticleEquipment {
  article_id: string;
  equipment_id: number;
  id: Generated<number>;
}

export interface AstronomicalObject {
  created_at: Generated<Date | null>;
  id: unknown;
  name: unknown;
}

export interface Equipment {
  aperture: Generated<number | null>;
  focal_length: Generated<number | null>;
  id: Generated<number>;
  link: string;
  name: string;
  pixel_size: Generated<number | null>;
  sensor_height: Generated<number | null>;
  sensor_width: Generated<number | null>;
  type_id: number;
}

export interface EquipmentType {
  id: Generated<number>;
  lang_key: string;
  priority: Generated<number>;
}

export interface Exposure {
  article_id: string;
  count: number;
  date: Date;
  exposure_time_s: number;
  id: Generated<number>;
  type: string;
}

export interface GalleryImage {
  alt_text: string;
  article_id: string;
  id: Generated<number>;
  name: string;
}

export interface Translations {
  key: string;
  lang: string;
  text: string;
}

export interface Visitors {
  date: Generated<Date>;
  id: Generated<number>;
  ip: string;
  page: string;
  user_agent: string;
}

export interface DB {
  account: Account;
  article: Article;
  article_equipment: ArticleEquipment;
  astronomical_object: AstronomicalObject;
  equipment: Equipment;
  equipment_type: EquipmentType;
  exposure: Exposure;
  gallery_image: GalleryImage;
  translations: Translations;
  visitors: Visitors;
}
